
import java.awt.Color;
import java.awt.Component;
import java.awt.Container;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DateEditor;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Diálogo de interfaz de usuario (JDialog) para la gestión del alta de nuevos
 * artículos en el sistema de inventario. Permite al usuario ingresar y validar
 * todos los datos necesarios para crear una nueva instancia de la clase.
 *
 * @author Antonio Naranjo Castillo
 */
public class AltaArticuloJDialog extends javax.swing.JDialog {

    // Declaración e iniciación de varialbles
    String codigo;
    String nombre;
    String categoria;
    String precio;
    String stock;
    String proveedor;
    String fechaFormateada;
    String garantia = "";
    String estado = "";
    String compatibilidad = "";
    String descripcionDet;

    Articulo articulo;
    List<String> listaArticulos = new ArrayList<>();

    // Variable estática para recuentar el número de artículos creados
    private static int articulosCreados;

    // Declaración de variables auxiliares
    int numMaxCaracteres;
    int itemSeleccionado;
    String formatoFecha = "dd/MM/yyyy";
    DateEditor editorFecha;
    Date fechaEntrada;
    SimpleDateFormat formateador;

    /**
     * Constructor del JDialog
     *
     * @param parent La ventana (JFrame) padre de la que depende este diálogo
     * @param modal Indica si el diálogo debe ser modal (true, bloqueando la
     * ventana padre) o no (false)
     */
    public AltaArticuloJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        // Formateando el JDialog
        this.getContentPane().setBackground(FormularioPrincipalJFrame.verde);
        formateaPanel(jPanelGarantia);
        formateaPanel(jPanelEstado);
        formateaPanel(jPanelComp);

        // Se formatea la representación que se muestra de la fecha de entrada del artículo en el constructor del JDialog
        editorFecha = new DateEditor(jSpinnerDateIn, formatoFecha);
        jSpinnerDateIn.setEditor(editorFecha);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox();
        tfPrecio = new javax.swing.JTextField();
        tfStock = new javax.swing.JTextField();
        tfProveedor = new javax.swing.JTextField();
        jSpinnerDateIn = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();
        jPanelGarantia = new javax.swing.JPanel();
        jLabelGarantia = new javax.swing.JLabel();
        rb12 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        rbSG = new javax.swing.JRadioButton();
        jPanelEstado = new javax.swing.JPanel();
        jLabelEstado = new javax.swing.JLabel();
        cbNuevo = new javax.swing.JCheckBox();
        cbReacondicionado = new javax.swing.JCheckBox();
        cbOfertaEsp = new javax.swing.JCheckBox();
        jPanelComp = new javax.swing.JPanel();
        jLabelComp = new javax.swing.JLabel();
        cbDebian = new javax.swing.JCheckBox();
        cbWindows = new javax.swing.JCheckBox();
        cbUbuntu = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfCodigo.setToolTipText("alfanumérico, máximo 10 caracteres");

        jLabel2.setText("Nombre del artículo:");

        jLabel3.setText("Categoría:");

        jLabel4.setText("Código de artículo:");

        jLabel5.setText("Precio unitario:");

        jLabel6.setText("Stock disponible:");
        jLabel6.setToolTipText("");

        jLabel7.setText("Proveedor:");

        jLabel8.setText("Fecha de entrada:");

        jLabel12.setText("Descripción detallada:");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir/Cancelar");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        tfNombre.setToolTipText("texto, máximo 50 caracteres");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordenador", "Portátil", "Monitor", "Impresora", "Accesorio", "Componente interno", "Otro" }));
        cbCategoria.setToolTipText("Selecciona una categoría");

        tfPrecio.setToolTipText("número con 2 decimales (máx 10000.00), punto como separador decimal");

        tfStock.setToolTipText("número entero mayor o igual que cero");

        tfProveedor.setToolTipText("texto, máximo 30 caracteres");

        jSpinnerDateIn.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerDateIn.setToolTipText("formato dd/mm/aaaa");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        taDescripcion.setToolTipText("Descripción detallada del artículo");
        jScrollPane1.setViewportView(taDescripcion);

        jPanelGarantia.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelGarantia.setText("Garantía:");

        buttonGroup1.add(rb12);
        rb12.setText("12 meses");
        rb12.setToolTipText("Garantía de 12 meses");

        buttonGroup1.add(rb24);
        rb24.setText("24 meses");
        rb24.setToolTipText("Garantía de 24 meses");

        buttonGroup1.add(rbSG);
        rbSG.setText("Sin garantía");
        rbSG.setToolTipText("Sin garantía");

        javax.swing.GroupLayout jPanelGarantiaLayout = new javax.swing.GroupLayout(jPanelGarantia);
        jPanelGarantia.setLayout(jPanelGarantiaLayout);
        jPanelGarantiaLayout.setHorizontalGroup(
            jPanelGarantiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGarantiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelGarantia)
                .addGap(96, 96, 96)
                .addComponent(rb12)
                .addGap(38, 38, 38)
                .addComponent(rb24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbSG)
                .addGap(46, 46, 46))
        );
        jPanelGarantiaLayout.setVerticalGroup(
            jPanelGarantiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGarantiaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGarantiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGarantia)
                    .addComponent(rb12)
                    .addComponent(rb24)
                    .addComponent(rbSG))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanelEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelEstado.setText("Estado del artículo:");

        cbNuevo.setText("Nuevo");
        cbNuevo.setToolTipText("Artículo nuevo");

        cbReacondicionado.setText("Reacondicionado");
        cbReacondicionado.setToolTipText("Artículo reacondicionado");

        cbOfertaEsp.setText("Oferta especial");
        cbOfertaEsp.setToolTipText("Artículo oferta especial");

        javax.swing.GroupLayout jPanelEstadoLayout = new javax.swing.GroupLayout(jPanelEstado);
        jPanelEstado.setLayout(jPanelEstadoLayout);
        jPanelEstadoLayout.setHorizontalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEstado)
                .addGap(50, 50, 50)
                .addComponent(cbNuevo)
                .addGap(49, 49, 49)
                .addComponent(cbReacondicionado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cbOfertaEsp)
                .addGap(29, 29, 29))
        );
        jPanelEstadoLayout.setVerticalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbOfertaEsp)
                    .addComponent(cbReacondicionado)
                    .addComponent(cbNuevo)
                    .addComponent(jLabelEstado))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanelComp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabelComp.setText("Compatibilidad:");

        cbDebian.setText("Debian");
        cbDebian.setToolTipText("Plataforma soportada Debian");

        cbWindows.setText("Windows");
        cbWindows.setToolTipText("Plataforma soportada Windows");

        cbUbuntu.setText("Ubuntu");
        cbUbuntu.setToolTipText("Plataforma soportada Ubuntu");

        javax.swing.GroupLayout jPanelCompLayout = new javax.swing.GroupLayout(jPanelComp);
        jPanelComp.setLayout(jPanelCompLayout);
        jPanelCompLayout.setHorizontalGroup(
            jPanelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelComp)
                .addGap(71, 71, 71)
                .addComponent(cbDebian)
                .addGap(47, 47, 47)
                .addComponent(cbWindows)
                .addGap(75, 75, 75)
                .addComponent(cbUbuntu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelCompLayout.setVerticalGroup(
            jPanelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbUbuntu)
                    .addComponent(cbWindows)
                    .addComponent(cbDebian)
                    .addComponent(jLabelComp))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel12)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfCodigo)
                                    .addComponent(tfNombre)
                                    .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfStock, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfProveedor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerDateIn))
                                .addGap(68, 68, 68))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(204, 204, 204)
                                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jPanelComp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelGarantia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jPanelComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de acción cuando se pulsa el botón "Guardar". Se encarga
     * de realizar todas las validaciones de los campos, procesar la lógica y
     * confirmar el almacenamiento de los datos.
     *
     * @param evt El evento de acción que se dispara al pulsar el botón.
     */
    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:

        // 1. Código de artículo: alfanumérico, máximo 10 caracteres.
        codigo = tfCodigo.getText();
        while (!validarCodigoAlfanumerico(codigo)) {
            codigo = JOptionPane.showInputDialog(
                    this,
                    "Existe un error --> Código de artículo: introduce un código alfanumérico, máximo 10 caracteres.",
                    "Solicitud del código",
                    JOptionPane.QUESTION_MESSAGE
            );
        }
        // Se muestra el contenido en el componentes y se imprime el resultado por consola
        tfCodigo.setText(codigo);
        System.out.println(String.format("El código %s es alfanumérico con un máximo de diez caracteres.", validarCodigoAlfanumerico(codigo) ? "SI" : "NO"));

        // 2. Nombre del artículo: texto, máximo 50 caracteres.
        numMaxCaracteres = 50;
        nombre = tfNombre.getText();
        while (!validarTexto(nombre, numMaxCaracteres)) {
            nombre = JOptionPane.showInputDialog(
                    this,
                    "Existe un error --> Nombre del artículo: introduce un texto, máximo 50 caracteres.",
                    "Solicitud del nombre del artículo",
                    JOptionPane.QUESTION_MESSAGE
            );
        }
        // Se muestra el contenido en el componentes y se imprime el resultado por consola
        tfNombre.setText(nombre);
        System.out.println(String.format("El nombre del artículo %s es texto con un máximo de %d caracteres.", validarTexto(nombre, numMaxCaracteres) ? "SI" : "NO", numMaxCaracteres));

        // 3. Categoría: lista desplegable con opciones como: Ordenador, Portátil, Monitor, Impresora, Accesorio, Componente interno, Otro.
        itemSeleccionado = cbCategoria.getSelectedIndex();
        categoria = cbCategoria.getItemAt(itemSeleccionado).toString();
        System.out.println(String.format("La categoría seleccionada ha sido: %s", categoria));

        // 4. Precio unitario: número con 2 decimales
        precio = tfPrecio.getText();
        while (!validarNumeroDosDecimales(precio)) {
            precio = JOptionPane.showInputDialog(
                    this,
                    "Existe un error --> Precio unitario: introduce un número menor de 10000.00 con 2 decimales empleando el punto como separador decimal.",
                    "Solicitud del precio del artículo",
                    JOptionPane.QUESTION_MESSAGE
            );
        }
        // Se muestra el contenido en el componentes y se imprime el resultado por consola
        tfPrecio.setText(precio);
        System.out.println(String.format("El precio introducido %s es un número con dos decimales y menor de 10000.00 €.", validarNumeroDosDecimales(precio) ? "SI" : "NO"));

        // 5. Stock disponible: número entero.
        stock = tfStock.getText();
        while (!validarEntero(stock)) {
            stock = JOptionPane.showInputDialog(
                    this,
                    "Existe un error --> Stock disponible: introduce un número entero.",
                    "Solicitud del stock del artículo",
                    JOptionPane.QUESTION_MESSAGE
            );
        }
        // Se muestra el contenido en el componentes y se imprime el resultado por consola
        tfStock.setText(stock);
        System.out.println(String.format("El número de stock introducido %s es un número entero.", validarEntero(stock) ? "SI" : "NO"));

        // 6. Proveedor: texto máximo 30 caracteres.
        numMaxCaracteres = 30;
        proveedor = tfProveedor.getText();
        while (!validarTexto(proveedor, numMaxCaracteres)) {
            proveedor = JOptionPane.showInputDialog(
                    this,
                    "Existe un error --> Proveedor: texto máximo 30 caracteres.",
                    "Solicitud del nombre del proveedor",
                    JOptionPane.QUESTION_MESSAGE
            );
        }
        // Se muestra el contenido en el componentes y se imprime el resultado por consola
        tfProveedor.setText(stock);
        System.out.println(String.format("El nombre del proveedor %s es texto con un máximo de %d caracteres.", validarTexto(proveedor, numMaxCaracteres) ? "SI" : "NO", numMaxCaracteres));

        // 7. Fecha de entrada: formato dd/mm/aaa. JSpinner
        // Se formatea la fecha según el patrón requerido dd/MM/yyyy
        fechaEntrada = (Date) jSpinnerDateIn.getValue();
        formateador = new SimpleDateFormat(formatoFecha);
        fechaFormateada = formateador.format(fechaEntrada);
        System.out.println(String.format("La fecha de entrada del artículo es: %s", fechaFormateada));

        // 8. Garantía: radio buttons para elegir entre 12 meses, 24 meses o Sin garantía
        do {
            if (!rb12.isSelected() && !rb24.isSelected() && !rbSG.isSelected()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Garantía: Seleccionar al menos una opción.",
                        "Error Garantía",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        } while (!rb12.isSelected() && !rb24.isSelected() && !rbSG.isSelected());

        // Se muestra el componente seleccionado y se imprime el resultado por consola
        if (rb12.isSelected()) {
            garantia = rb12.getText();
            System.out.println(String.format("La garantía seleccionada ha sido: %s", garantia));
        } else if (rb24.isSelected()) {
            garantia = rb24.getText();
            System.out.println(String.format("La garantía seleccionada ha sido: %s", garantia));
        } else if (rbSG.isSelected()) {
            garantia = rbSG.getText();
            System.out.println(String.format("La garantía seleccionada ha sido: %s", garantia));
        }

        // 9. Estado del artículo (checkboxes): Nuevo, Reacondicionado, Oferta especial (pueden seleccionarse varias)
        // Se imprime el resultado por consola de los componentes seleccionados
        if (cbNuevo.isSelected() & cbReacondicionado.isSelected() & cbOfertaEsp.isSelected()) {
            estado = String.format("%s + %s + %s", cbNuevo.getText(), cbReacondicionado.getText(), cbOfertaEsp.getText());
            System.out.println(String.format("El estado del artículo es: %s", estado));
        } else if (cbReacondicionado.isSelected() & cbOfertaEsp.isSelected()) {
            estado = String.format("%s + %s", cbReacondicionado.getText(), cbOfertaEsp.getText());
            System.out.println(String.format("El estado del artículo es: %s", estado));
        } else if (cbNuevo.isSelected() & cbOfertaEsp.isSelected()) {
            estado = String.format("%s + %s", cbNuevo.getText(), cbOfertaEsp.getText());
            System.out.println(String.format("El estado del artículo es: %s", estado));
        } else if (cbNuevo.isSelected() & cbReacondicionado.isSelected()) {
            estado = String.format("%s + %s", cbNuevo.getText(), cbReacondicionado.getText());
            System.out.println(String.format("El estado del artículo es: %s", estado));
        } else if (cbOfertaEsp.isSelected()) {
            estado = cbOfertaEsp.getText();
            System.out.println(String.format("El estado del artículo es: %s", estado));
        } else if (cbReacondicionado.isSelected()) {
            estado = cbReacondicionado.getText();
            System.out.println(String.format("El estado del artículo es: %s", estado));
        } else if (cbNuevo.isSelected()) {
            estado = cbNuevo.getText();
            System.out.println(String.format("El estado del artículo es: %s", estado));
        }

        // 10. Compatibilidad: Indicar sistemas operativos o plataformas compatibles. Al menos una (checkboxes) de: Windows, Ububtu, Debian
        do {
            if (!cbWindows.isSelected() && !cbUbuntu.isSelected() && !cbDebian.isSelected()) {
                JOptionPane.showMessageDialog(
                        this,
                        "Compatibilidad: Indicar al menos un sistema operativo o plataforma compatible.",
                        "Error Compatibilidad",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        } while (!cbWindows.isSelected() && !cbUbuntu.isSelected() && !cbDebian.isSelected());

        // Se imprime el resultado por consola de los componentes seleccionados
        if (cbWindows.isSelected() & cbUbuntu.isSelected() & cbDebian.isSelected()) {
            compatibilidad = String.format("%s + %s + %s", cbWindows.getText(), cbUbuntu.getText(), cbDebian.getText());
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        } else if (cbUbuntu.isSelected() & cbDebian.isSelected()) {
            compatibilidad = String.format("%s + %s", cbUbuntu.getText(), cbDebian.getText());
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        } else if (cbWindows.isSelected() & cbDebian.isSelected()) {
            compatibilidad = String.format("%s + %s", cbWindows.getText(), cbDebian.getText());
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        } else if (cbWindows.isSelected() & cbUbuntu.isSelected()) {
            compatibilidad = String.format("%s + %s", cbWindows.getText(), cbUbuntu.getText());
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        } else if (cbDebian.isSelected()) {
            compatibilidad = cbDebian.getText();
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        } else if (cbUbuntu.isSelected()) {
            compatibilidad = cbUbuntu.getText();
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        } else if (cbWindows.isSelected()) {
            compatibilidad = cbWindows.getText();
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", compatibilidad));
        }

        // 11. Descripción detallada: área de texto multilínea (JTextArea) para información extra.
        do {
            if (taDescripcion.getText().isEmpty() || taDescripcion.getText() == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Descripción detallada: Debe redactar una breve descripción del artículo.",
                        "Error descripción detallada",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }
        } while (taDescripcion.getText().isEmpty());
        // Se imprime el resultado por consola de los componentes seleccionados
        descripcionDet = taDescripcion.getText();
        System.out.println(String.format("La descripción detallada del artículo es: %s", descripcionDet));

        // Guardar registro en una lista de artículos
        articulo = new Articulo(codigo, nombre, categoria, precio, stock, proveedor, fechaFormateada, garantia, estado, compatibilidad, descripcionDet);
        listaArticulos.add(articulo.toString());

        // Mensaje salida
        JOptionPane.showMessageDialog(this, "Registro guardado.");
        // Se muestran los artículos almacenados en la ArrayList por consola
        System.out.println("Lista de artículos:");
        for (String str : listaArticulos) {
            System.out.println(str);
        }
        System.out.println("---------------");
        // A modo de comprobación, se muestra el último artículo almacenado por showMessageDialog
        JOptionPane.showMessageDialog(this, listaArticulos.get(listaArticulos.size() - 1));

        // Limpiar todos los componentes
        limpiarTodos();

    }//GEN-LAST:event_botonGuardarActionPerformed

    /**
     * Maneja el evento de acción cuando se pulsa el botón "Salir". Se encarga
     * de cerrar el diálogo actual (JDialog) y liberar sus recursos.
     *
     * @param evt El evento de acción que se dispara al pulsar el botón.
     */
    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:

        // Se recuentan los campos modificados y se evalua la respuesta del usuario mediante un JOptionPane
        if (contarCamposModificados(this.getContentPane()) > 0) {
            // Mensajes de salida 
            int seleccion = JOptionPane.showConfirmDialog(
                    this,
                    "Existen campos completados sin guardar ¿desea salir sin guardar cambios?",
                    "Salir del inventario",
                    JOptionPane.YES_NO_OPTION
            );
            // Si se selecciona la opción Sí, se procede a salir del aplicativo sin guardar cambios
            if (seleccion == JOptionPane.YES_OPTION) {
                // Se llama al constructor del JDialog
                this.dispose();

                // Limpiar todos los componentes
                limpiarTodos();
            }
        } else {
            // Se llama al constructor del JDialog sin limpiar los campos
            this.dispose();
        }
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * Método principal del JDialog
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AltaArticuloJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AltaArticuloJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AltaArticuloJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AltaArticuloJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AltaArticuloJDialog dialog = new AltaArticuloJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });

    }

    /**
     * El método validarCodigoAlfanumerico comprueba si el String aportado como
     * argumento cumple con una determinada expresión regular, el código debe
     * ser alfanumérico y admite hasta un máximo de 10 caracteres.
     *
     * @param texto String a comprobar si comple con el patrón alfanumérico
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarCodigoAlfanumerico(String texto) {

        // Definir la Expresión Regular del código alfanumérico, entre uno y diez caracteres
        String regex = "^[a-zA-Z0-9]{1,10}$";

        return texto.matches(regex);
    }

    /**
     * El método validarNombre comprueba si el String aportado como argumento
     * cumple con una determinada expresión regular, en este caso admite
     * cualqueir caracter pero hasta un máximo de 50 caracteres.
     *
     * @param texto String a comprobar si comple con el patrón máximo 50
     * caracteres
     * @param numCaracteres Número entero para indicar el máximo de caracteres
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarTexto(String texto, int numCaracteres) {

        // Definir la Expresión Regular para chequear el nombre del artículo, texto, entre uno y un máximo de 50 caracteres
        String regex = String.format("^.{1,%d}$", numCaracteres);

        return texto.matches(regex);
    }

    /**
     * El método validarNumeroDosDecimales comprueba si el String aportado como
     * argumento cumple con una determinada expresión regular, en este caso
     * admite cualquier digito, pero es obligatorio que contenga dos decimales.
     *
     * @param texto String a comprobar si cumple con el patrón número con dos
     * decimales
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarNumeroDosDecimales(String texto) {

        // Expresión regular que admite números con dos decimales, punto como separador decimal
        String regex = "^\\d+\\.\\d{2}$";

        final Double PRECIO_MAX = 10000.0;

        // Si se produce match entonces se evalua si el número decimal es mayor de 10000.00
        if (texto.matches(regex) && Double.parseDouble(texto) <= PRECIO_MAX) {
            return true;
        } else {
            return false;

        }

    }

    /**
     * El método validarEntero comprueba si el String aportado como argumento
     * cumple con una determinada expresión regular, en este caso admite
     * cualquier digito tal que el número resultante sea un entero (sin
     * decimales).
     *
     * @param texto String a comprobar si cumple con el patrón número entero
     * incluyendo el cero
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarEntero(String texto) {

        // Definir la Expresión Regular para chequear el nombre del artículo, texto, máximo 50 caracteres
        String regex = "^\\d+$";

        return texto.matches(regex);
    }

    /**
     * Limpia todos los campos de entrada dentro de un contenedor dado.
     *
     * @param contenedor El contenedor a limpiar
     */
    public void limpiarCampos(Container contenedor) {

        // Se crea una lista de componentes que contiene un contenedor
        Component[] componentes = contenedor.getComponents();

        // Por cada componente del contenedor, dependiendo de qué tipo de componente sea lo limpia o desmarca
        for (Component componente : componentes) {

            if (componente instanceof JTextField) {
                ((JTextField) componente).setText("");
            } else if (componente instanceof JCheckBox) {
                ((JCheckBox) componente).setSelected(false);
            } else if (componente instanceof JComboBox) {
                ((JComboBox) componente).setSelectedIndex(0);
            } else if (componente instanceof JSpinner) {
                ((JSpinner) componente).setValue(new Date());
            }
        }
    }

    // Método para limpiar todos los componestes de un contenedor y un grupo de radio botones así como el text area.
    public void limpiarTodos() {

        limpiarCampos(this.getContentPane());
        buttonGroup1.clearSelection();
        taDescripcion.setText("");

    }

    /**
     * Limpia todos los campos de entrada dentro de un contenedor dado.
     *
     * @param contenedor El contenedor sobre el cual supervisar cambios.
     * @return Contador número entero contador de campos modificados sin guardar
     */
    public int contarCamposModificados(Container contenedor) {

        // Se crea una lista de componentes que contiene un contenedor
        Component[] componentes = contenedor.getComponents();
        // contador
        int contador = 0;

        // Por cada componente del contenedor, dependiendo de qué tipo de componente sea lo limpia o desmarca
        for (Component componente : componentes) {

            if (componente instanceof JTextField && !((JTextField) componente).getText().isEmpty()) {
                contador++;
            } else if (componente instanceof JCheckBox && ((JCheckBox) componente).isSelected()) {
                contador++;
            } else if (componente instanceof JRadioButton && ((JRadioButton) componente).isSelected()) {
                contador++;
            }
        }
        return contador;
    }

    /**
     * Aplica un formato a un contenedor y a sus componentes internos. Este
     * método establece el color de fondo del contenedor al color azul
     * predefinido y asigna el color blanco al texto de todas las etiquetas,
     * botones de radio y casillas de verificación que se encuentren
     * directamente dentro de él.
     *
     * @param contenedor El contenedor al que se aplicará el formato.
     */
    public static void formateaPanel(Container contenedor) {

        // Se formatea el fondo del panel
        contenedor.setBackground(FormularioPrincipalJFrame.azulClaro);
        // Se crea una lista de componentes que contiene el panel
        Component[] componentes = contenedor.getComponents();

        // Por cada componente del panel si es una etiqueta formatea el texto con color blanco
        for (Component componente : componentes) {
            if (componente instanceof JLabel) {
                ((JLabel) componente).setForeground(Color.WHITE);
            } else if (componente instanceof JRadioButton) {
                ((JRadioButton) componente).setForeground(Color.WHITE);
            } else if (componente instanceof JCheckBox) {
                ((JCheckBox) componente).setForeground(Color.WHITE);
            }
        }
    }

    /**
     * Clase que representa un artículo dentro de un inventario. Esta clase
     * almacena toda la información relevante de un artículo.
     *
     * @author Antonio Naranjo Castillo
     */
    public class Articulo {

        private final String codigo;
        private final String nombre;
        private final String categoria;
        private final String precio;
        private final String stock;
        private final String proveedor;
        private final String fechaEntrada;
        private final String garantia;
        private final String estado;
        private final String compatibilidad;
        private final String descripcionDetallada;

        /**
         * Constructor objeto Articulo.
         *
         * @param codigo El código único del artículo (alfanumérico, máx. 10
         * caracteres).
         * @param nombre El nombre del artículo.
         * @param categoria La categoría a la que pertenece el artículo.
         * @param precio El precio de venta del artículo, número con dos
         * decimales
         * @param stock La cantidad actual de unidades en inventario.
         * @param proveedor El nombre o identificador del proveedor.
         * @param fechaEntrada La fecha en que el artículo fue registrado en el
         * sistema (formato dd/MM/yyyy).
         * @param garantia El período de garantía del artículo.
         * @param estado El estado actual del artículo.
         * @param compatibilidad Los sistemas operativos o plataformas
         * compatibles.
         * @param descripcionDetallada Una descripción extensa y detallada del
         * producto.
         */
        public Articulo(String codigo, String nombre, String categoria, String precio, String stock, String proveedor, String fechaEntrada, String garantia, String estado, String compatibilidad, String descripcionDetallada) {
            this.codigo = codigo;
            this.nombre = nombre;
            this.categoria = categoria;
            this.precio = precio;
            this.stock = stock;
            this.proveedor = proveedor;
            this.fechaEntrada = fechaEntrada;
            this.garantia = garantia;
            this.estado = estado;
            this.compatibilidad = compatibilidad;
            this.descripcionDetallada = descripcionDetallada;
            AltaArticuloJDialog.articulosCreados++;

        }

        /**
         * Genera una representación en formato String del objeto Articulo,
         * incluyendo el contador global de artículos creados.
         *
         * @return Una cadena formateada que lista todos los atributos del
         * artículo.
         */
        @Override
        public String toString() {

            return String.format("Artículo %d: {Código: %s, Nombre: %s, Categoría: %s, Precio: %s, Stock: %s, Proveedor: %s, Fecha entrada: %s, Garantía: %s, Estado: %s, Compatibilidad: %s, Descripción detallada: %s}", AltaArticuloJDialog.articulosCreados, this.codigo, this.nombre, this.categoria, this.precio, this.stock, this.proveedor, this.fechaEntrada, this.garantia, this.estado, this.compatibilidad, this.descripcionDetallada);

        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JCheckBox cbDebian;
    private javax.swing.JCheckBox cbNuevo;
    private javax.swing.JCheckBox cbOfertaEsp;
    private javax.swing.JCheckBox cbReacondicionado;
    private javax.swing.JCheckBox cbUbuntu;
    private javax.swing.JCheckBox cbWindows;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelComp;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelGarantia;
    private javax.swing.JPanel jPanelComp;
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JPanel jPanelGarantia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDateIn;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rbSG;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfProveedor;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables
}
