
import java.awt.Color;
import java.awt.Font;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Ventana principal (JFrame) de la aplicación. Sirve como el contenedor de
 * nivel superior y la interfaz principal desde donde se gestionan y lanzan
 * todos los demás módulos de la aplicación, como los diálogos de alta o
 * consulta.
 *
 * @author Antonio Naranjo Castillo
 */
public class FormularioPrincipalJFrame extends javax.swing.JFrame {

    // Declaración/instanciación de variables
    AltaArticuloJDialog dialogo = new AltaArticuloJDialog(this, true);

    // Colores
    public static Color azulOscuro = new Color(0, 19, 59);
    public static Color azulClaro = new Color(0, 148, 181);
    public static Color verde = new Color(2, 196, 178);

    /**
     * Constructor del JFrame
     */
    public FormularioPrincipalJFrame() {
        initComponents();
        // Formateo del formulario principal
        this.getContentPane().setBackground(FormularioPrincipalJFrame.azulOscuro);
        jButtonAnadirArticulo.setBackground(FormularioPrincipalJFrame.verde);
        jButtonAnadirArticulo.setForeground(FormularioPrincipalJFrame.azulOscuro);
        jButtonAnadirArticulo.setFont(new Font("Lucida Console", Font.BOLD, 11));
        jMenuPrincipal.setFont(new Font("Lucida Console", Font.BOLD, 11));
        jMenuItemAnadir.setFont(new Font("Lucida Console", Font.PLAIN, 11));
        jMenuItemSalir.setFont(new Font("Lucida Console", Font.PLAIN, 11));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAnadirArticulo = new javax.swing.JButton();
        imagenLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuPrincipal = new javax.swing.JMenu();
        jMenuItemAnadir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonAnadirArticulo.setForeground(new java.awt.Color(0, 19, 59));
        jButtonAnadirArticulo.setText("Añadir un artículo");
        jButtonAnadirArticulo.setToolTipText("Pulsa sobre el botón para añadir un artículo");
        jButtonAnadirArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnadirArticuloActionPerformed(evt);
            }
        });

        imagenLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logoATM.png"))); // NOI18N

        jMenuPrincipal.setText("Gestión de inventario");
        jMenuPrincipal.setToolTipText("Menú gestión de inventario");

        jMenuItemAnadir.setText("Añadir Artículo");
        jMenuItemAnadir.setToolTipText("Pulsar para añadir un artículo nuevo");
        jMenuItemAnadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAnadirActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemAnadir);
        jMenuPrincipal.add(jSeparator1);

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.setToolTipText("Pulsar para salir del programa");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuPrincipal.add(jMenuItemSalir);

        jMenuBar1.add(jMenuPrincipal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAnadirArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(imagenLogo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagenLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jButtonAnadirArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Maneja el evento de acción del elemento de menú 1. Se encarga de
     * instanciar y mostrar el diálogo de alta (AltaArticuloJDialog).
     *
     * @param evt El evento de acción que se dispara al seleccionar el elemento
     * de menú.
     */
    private void jMenuItemAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAnadirActionPerformed
        // TODO add your handling code here:
        dialogo.setVisible(true);
    }//GEN-LAST:event_jMenuItemAnadirActionPerformed

    /**
     * Maneja el evento de acción del elemento de menú 2. Salir del programa con
     * éxito.
     *
     * @param evt El evento de acción que se dispara al seleccionar el elemento
     * de menú.
     */
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSalirActionPerformed

    /**
     * Maneja el evento de acción cuando se pulsa el botón "Añadir Artículo". Se
     * encarga de instanciar y mostrar el diálogo de alta (AltaArticuloJDialog).
     *
     * @param evt El evento de acción que se dispara al pulsar el botón.
     */
    private void jButtonAnadirArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnadirArticuloActionPerformed
        // TODO add your handling code here:
        dialogo.setVisible(true);
    }//GEN-LAST:event_jButtonAnadirArticuloActionPerformed

    /**
     * Método principal de JFrame
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipalJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipalJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imagenLogo;
    private javax.swing.JButton jButtonAnadirArticulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAnadir;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuPrincipal;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
