
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anaranjo
 */
public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    public NewJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jOptionPane1 = new javax.swing.JOptionPane();
        tfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        cbCategoria = new javax.swing.JComboBox();
        tfPrecio = new javax.swing.JTextField();
        tfStock = new javax.swing.JTextField();
        tfProveedor = new javax.swing.JTextField();
        jSpinnerDateIn = new javax.swing.JSpinner();
        rb12 = new javax.swing.JRadioButton();
        rb24 = new javax.swing.JRadioButton();
        rbSG = new javax.swing.JRadioButton();
        cbNuevo = new javax.swing.JCheckBox();
        cbReacondicionado = new javax.swing.JCheckBox();
        cbOfertaEsp = new javax.swing.JCheckBox();
        cbWindows = new javax.swing.JCheckBox();
        cbUbuntu = new javax.swing.JCheckBox();
        cbDebian = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescripcion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tfCodigo.setToolTipText("alfanumérico, máximo 10 caracteres");

        jLabel2.setText("Nombre del artículo:");

        jLabel3.setText("Categoría:");

        jLabel4.setText("Código de artículo:");

        jLabel5.setText("Precio unitario:");

        jLabel6.setText("Stock disponible:");
        jLabel6.setToolTipText("");

        jLabel7.setText("Proveedor:");

        jLabel8.setText("Fecha de entrada:");

        jLabel9.setText("Garantía:");

        jLabel10.setText("Estado del artículo");

        jLabel11.setText("Compatibilidad:");

        jLabel12.setText("Descripción detallada:");

        botonGuardar.setText("Guardar");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });

        botonSalir.setText("Salir/Cancelar");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        tfNombre.setToolTipText("texto, máximo 50 caracteres");

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ordenador", "Portátil", "Monitor", "Impresora", "Accesorio", "Componente interno", "Otro" }));
        cbCategoria.setToolTipText("Selecciona una categoría");

        tfPrecio.setToolTipText("número con 2 decimales (máx 10000.00), punto como separador decimal");

        tfStock.setToolTipText("número entero mayor o igual que cero");

        tfProveedor.setToolTipText("texto, máximo 30 caracteres");

        jSpinnerDateIn.setModel(new javax.swing.SpinnerDateModel());
        jSpinnerDateIn.setToolTipText("formato dd/mm/aaaa");

        buttonGroup1.add(rb12);
        rb12.setText("12 meses");
        rb12.setToolTipText("Garantía de 12 meses");

        buttonGroup1.add(rb24);
        rb24.setText("24 meses");
        rb24.setToolTipText("Garantía de 24 meses");

        buttonGroup1.add(rbSG);
        rbSG.setText("Sin garantía");
        rbSG.setToolTipText("Sin garantía");

        cbNuevo.setText("Nuevo");
        cbNuevo.setToolTipText("Artículo nuevo");

        cbReacondicionado.setText("Reacondicionado");
        cbReacondicionado.setToolTipText("Artículo reacondicionado");

        cbOfertaEsp.setText("Oferta especial");
        cbOfertaEsp.setToolTipText("Artículo oferta especial");

        cbWindows.setText("Windows");
        cbWindows.setToolTipText("Plataforma soportada Windows");

        cbUbuntu.setText("Ubuntu");
        cbUbuntu.setToolTipText("Plataforma soportada Ubuntu");

        cbDebian.setText("Debian");
        cbDebian.setToolTipText("Plataforma soportada Debian");

        taDescripcion.setColumns(20);
        taDescripcion.setRows(5);
        taDescripcion.setToolTipText("Descripción detallada del artículo");
        jScrollPane1.setViewportView(taDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfCodigo)
                            .addComponent(tfNombre)
                            .addComponent(cbCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfStock, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfProveedor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSpinnerDateIn)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb12)
                            .addComponent(cbNuevo)
                            .addComponent(cbWindows))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(rb24)
                                .addGap(55, 55, 55))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbUbuntu)
                                    .addComponent(cbReacondicionado))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbOfertaEsp)
                            .addComponent(rbSG)
                            .addComponent(cbDebian))
                        .addGap(45, 45, 45))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(botonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(botonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jSpinnerDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(rb12)
                    .addComponent(rb24)
                    .addComponent(rbSG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cbNuevo)
                    .addComponent(cbReacondicionado)
                    .addComponent(cbOfertaEsp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbWindows)
                    .addComponent(cbUbuntu)
                    .addComponent(cbDebian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardar)
                    .addComponent(botonSalir))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        // TODO add your handling code here:
        String codigo = tfCodigo.getText();
        System.out.println(String.format("El código %s es alfanumérico con un máximo de diez caracteres.", validarCodigoAlfanumerico(codigo) ? "SI" : "NO"));

        int numCaracteres;
        numCaracteres = 50;
        String nombre = tfNombre.getText();
        System.out.println(String.format("El nombre del artículo %s es texto con un máximo de %d caracteres.", validarTexto(nombre, numCaracteres) ? "SI" : "NO", numCaracteres));

        int itemSeleccionado;
        itemSeleccionado = cbCategoria.getSelectedIndex();
        String categoria;
        categoria = cbCategoria.getItemAt(itemSeleccionado).toString();
        System.out.println(String.format("La categoría seleccionada ha sido: %s", categoria));

        String precio = tfPrecio.getText();
        System.out.println(String.format("El número introducido %s es un número con dos decimales.", validarNumeroDosDecimales(precio) ? "SI" : "NO"));

        String stock = tfStock.getText();
        System.out.println(String.format("El número introducido %s es un número entero.", validarEntero(stock) ? "SI" : "NO"));

        numCaracteres = 30;
        String proveedor = tfProveedor.getText();
        System.out.println(String.format("El nombre del proveedor %s es texto con un máximo de %d caracteres.", validarTexto(proveedor, numCaracteres) ? "SI" : "NO", numCaracteres));

        String fechaEntrada = jSpinnerDateIn.getValue().toString();
        System.out.println(String.format("La fecha de entrada del artículo es: %s", fechaEntrada));
        // Se formatea la fecha según el patrón requerido dd/MM/yyyy
        Date fechaSeleccionada = (Date) jSpinnerDateIn.getValue();
        SimpleDateFormat formateador = new SimpleDateFormat("dd/MM/yyyy");
        String fechaFormateada = formateador.format(fechaSeleccionada);
        System.out.println(String.format("La fecha de entrada del artículo es: %s", fechaFormateada));

        if (rb12.isSelected()) {
            System.out.println(String.format("La garantía seleccionada ha sido: %s", rb12.getText()));
        } else if (rb24.isSelected()) {
            System.out.println(String.format("La garantía seleccionada ha sido: %s", rb24.getText()));
        } else if (rbSG.isSelected()) {
            System.out.println(String.format("La garantía seleccionada ha sido: %s", rbSG.getText()));
        }

        if (cbNuevo.isSelected()) {
            System.out.println(String.format("El estado del artículo es: %s", cbNuevo.getText()));
        }
        if (cbReacondicionado.isSelected()) {
            System.out.println(String.format("El estado del artículo es: %s", cbReacondicionado.getText()));
        }
        if (cbOfertaEsp.isSelected()) {
            System.out.println(String.format("El estado del artículo es: %s", cbOfertaEsp.getText()));
        }

        if (cbWindows.isSelected()) {
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", cbWindows.getText()));
        }
        if (cbUbuntu.isSelected()) {
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", cbUbuntu.getText()));
        }
        if (cbDebian.isSelected()) {
            System.out.println(String.format("La plataforma soportada por el artículo es: %s", cbDebian.getText()));
        }

        System.out.println(String.format("La descripción detallada del artículo es: %s", taDescripcion.getText()));
        
        
        // Mensajes de salida 
        JFrame framePadre = null;
        JOptionPane.showMessageDialog(
            framePadre, 
            "Bienvenido al sistema de validación.", 
            "Mensaje de Inicio", 
            JOptionPane.INFORMATION_MESSAGE
        );
        String nombreUsuario = JOptionPane.showInputDialog(
            framePadre,
            "Por favor, introduce tu nombre:",
            "Solicitud de Datos",
            JOptionPane.QUESTION_MESSAGE
        );
        if (nombreUsuario != null && !nombreUsuario.trim().isEmpty()) {
            JOptionPane.showMessageDialog(framePadre, "Hola, " + nombreUsuario + ".");
        } else {
            JOptionPane.showMessageDialog(framePadre, "No se introdujo un nombre.");
        }
        
        
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NewJDialog dialog = new NewJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    /**
     * El método validarCodigoAlfanumerico comprueba si el String aportado como
     * argumento cumple con una determinada expresión regular, el código debe
     * ser alfanumérico y admite hasta un máximo de 10 caracteres.
     *
     * @param texto String a comprobar si comple con el patrón alfanumérico
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarCodigoAlfanumerico(String texto) {

        // Definir la Expresión Regular del código alfanumérico, entre uno y diez caracteres
        String regex = "^[a-zA-Z0-9]{1,10}$";

        return texto.matches(regex);
    }

    /**
     * El método validarNombre comprueba si el String aportado como argumento
     * cumple con una determinada expresión regular, en este caso admite
     * cualqueir caracter pero hasta un máximo de 50 caracteres.
     *
     * @param texto String a comprobar si comple con el patrón máximo 50
     * caracteres
     * @param numCaracteres Número entero para indicar el máximo de caracteres
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarTexto(String texto, int numCaracteres) {

        // Definir la Expresión Regular para chequear el nombre del artículo, texto, máximo 50 caracteres
        String regex = String.format("^.{1,%d}$", numCaracteres);

        return texto.matches(regex);
    }

    /**
     * El método validarNumeroDosDecimales comprueba si el String aportado como
     * argumento cumple con una determinada expresión regular, en este caso
     * admite cualquier digito, pero es obligatorio que contenga dos decimales.
     *
     * @param texto String a comprobar si comple con el patrón número con dos
     * decimales
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarNumeroDosDecimales(String texto) {

        // Expresión regular que admite números con dos decimales, punto como separador decimal
        String regex = "^\\d+\\.\\d{2}$";

        final Double PRECIO_MAX = 10000.0;

        // Si se produce match entonces se evalua si el número decimal es mayo de 10000
        if (texto.matches(regex) && Double.parseDouble(texto) <= PRECIO_MAX) {
            return true;
        } else {
            return false;

        }

    }

    /**
     * El método validarEntero comprueba si el String aportado como argumento
     * cumple con una determinada expresión regular, en este caso admite
     * cualquier digito tal que el número resultante sea cero.
     *
     * @param texto String a comprobar si comple con el patrón número entero
     * incluyendo el cero
     * @return Booleano indicando true si se establece match con el texto pasado
     * como argumento
     */
    public boolean validarEntero(String texto) {

        // Definir la Expresión Regular para chequear el nombre del artículo, texto, máximo 50 caracteres
        String regex = "^\\d+$";

        return texto.matches(regex);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cbCategoria;
    private javax.swing.JCheckBox cbDebian;
    private javax.swing.JCheckBox cbNuevo;
    private javax.swing.JCheckBox cbOfertaEsp;
    private javax.swing.JCheckBox cbReacondicionado;
    private javax.swing.JCheckBox cbUbuntu;
    private javax.swing.JCheckBox cbWindows;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerDateIn;
    private javax.swing.JRadioButton rb12;
    private javax.swing.JRadioButton rb24;
    private javax.swing.JRadioButton rbSG;
    private javax.swing.JTextArea taDescripcion;
    private javax.swing.JTextField tfCodigo;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    private javax.swing.JTextField tfProveedor;
    private javax.swing.JTextField tfStock;
    // End of variables declaration//GEN-END:variables
}
